### ISSUE TITLE
"/home/wiremock/storage": must be unique'

### ISSUE THREAD

**Issue by dicolasi** [gitkent/helm-charts#7]
I am trying to deploy the chart using helm 2. 
I am having the following error:

`spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value.`

Think the problem is here: 

```
          volumeMounts:
          - mountPath: /home/wiremock/storage
            name: mappings-data
          - mountPath: /home/wiremock/storage
            name: responses-data
```
